âœ-venv/lib/python3.6/site-packages/zmq/error.py 2pyXÅh